spring:
  application:
    name: springboot-rabbitmq-sender
  rabbitmq:
    host: 192.168.50.103
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    publisher-returns: false
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
server:
  port: 8096