spring:
  application:
    name: sender-test
  rabbitmq:
    host: 192.168.50.103
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
server:
  port: 8078
