server:
  port: 8080
spring:
  application:
    name: springboot-mybatis-non-annotated
  datasource:
    username: mysql
    password: v12345
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.6.229:3306/Sunflower_new?useUnicode=true&useSSL=false&amp;characterEncoding=utf-8"
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-return: true
      test-while-idle: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
    tomcat:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  type-aliases-package: com.vpiaotong.springboot.entity
  mapper-locations: classpath*:com/vpiaotong/springboot/dao/**/mapping/**/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql