server:
  port: 8080
spring:
  application:
    name: springboot-redis
  redis:
    host: 172.16.6.211
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 6000ms